add_newline = false

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
truncation_length = 3
style = "bold cyan"

[git_branch]
symbol = "ğŸŒ± "
style = "bold purple"

[git_status]
style = "bold yellow"

[kubernetes]
format = 'on [â˜¸ $context ($namespace)](bold blue) '
disabled = false

[python]
format = 'via [ğŸ $version]($style) '
style = "yellow bold"

[cmd_duration]
min_time = 500
format = "took [$duration](bold red)"

[nodejs]
symbol = "â¬¢ "

[rust]
symbol = "ğŸ¦€ "

[golang]
symbol = "ğŸ¹ "
